// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA8YgBATZgxbRPwibDa2o2s-arrG21yDM',
    appId: '1:103332765780:web:ad27066911ce3f3635cdc1',
    messagingSenderId: '103332765780',
    projectId: 'neom-e4c49',
    authDomain: 'neom-e4c49.firebaseapp.com',
    storageBucket: 'neom-e4c49.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuslNKtzEC6k2QLtA_RX9MH0i4vZn8kNI',
    appId: '1:103332765780:android:cf268cdf7358b1fd35cdc1',
    messagingSenderId: '103332765780',
    projectId: 'neom-e4c49',
    storageBucket: 'neom-e4c49.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVzYLjC-v4SQNL_27uq1OYG8N4F7UDzy8',
    appId: '1:103332765780:ios:ba14198780379d2b35cdc1',
    messagingSenderId: '103332765780',
    projectId: 'neom-e4c49',
    storageBucket: 'neom-e4c49.appspot.com',
    iosClientId: '103332765780-06oiaa9rsbd1kbga55md4bj1nls1sd74.apps.googleusercontent.com',
    iosBundleId: 'com.example.neom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVzYLjC-v4SQNL_27uq1OYG8N4F7UDzy8',
    appId: '1:103332765780:ios:ba14198780379d2b35cdc1',
    messagingSenderId: '103332765780',
    projectId: 'neom-e4c49',
    storageBucket: 'neom-e4c49.appspot.com',
    iosClientId: '103332765780-06oiaa9rsbd1kbga55md4bj1nls1sd74.apps.googleusercontent.com',
    iosBundleId: 'com.example.neom',
  );
}
